name: semester_projectvault
description: "A Flutter project for semester submission."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  firebase_core: ^4.2.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  shared_preferences: ^2.5.3
  firebase_storage: ^13.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets for images, icons, and animations
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # Fonts are handled by Google Fonts package, no need to include local fonts
